// Generate Ideas Tab - Phase 3: UI Components

import React, { useState, useMemo, useCallback } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { DataTable } from '@/components/composition/DataTable';
import { getContentIdeaColumns } from '../columns/contentIdeaColumns';
import { 
  useContentIdeas,
  useDeleteContentIdea,
  useCreateBriefFromIdea,
  useContentTypeOptions,
  useAutoGenerateIdeas
} from '@/hooks/content-creation';
import type { 
  ContentIdeaWithDetails,
  ContentIdeaFilters
} from '@/types/content-creation';
import { CONTENT_STATUSES } from '@/types/content-creation';
import { 
  Plus, 
  Search, 
  Lightbulb,
  Sparkles,
  Filter,
  Download,
  Bot,
  Trash2
} from 'lucide-react';
import { EmptyState } from '@/components/ui/empty-state';
import { Skeleton } from '@/components/ui/skeleton';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog';
import { toast } from 'sonner';
import { AutoGenerateDialog, type AutoGenerateFormData } from '../components/AutoGenerateDialog';

interface GenerateIdeasTabProps {
  onCreateIdea: () => void;
  onEditIdea: (idea: ContentIdeaWithDetails) => void;
  onCreateBrief: (idea: ContentIdeaWithDetails) => void;
  onViewBrief?: (briefId: string) => void;
  className?: string;
}

export const GenerateIdeasTab = React.memo<GenerateIdeasTabProps>(({
  onCreateIdea,
  onEditIdea,
  onCreateBrief,
  onViewBrief,
  className
}) => {
  // State management
  const [searchQuery, setSearchQuery] = useState('');
  const [statusFilter, setStatusFilter] = useState<string>('all');
  const [contentTypeFilter, setContentTypeFilter] = useState<string>('all');
  const [selectedItems, setSelectedItems] = useState<string[]>([]);
  const [sortBy, setSortBy] = useState<string>('created_at');
  const [sortOrder, setSortOrder] = useState<'asc' | 'desc'>('desc');
  const [deleteIdea, setDeleteIdea] = useState<ContentIdeaWithDetails | null>(null);
  const [page, setPage] = useState(1);
  const [showAutoGenerateDialog, setShowAutoGenerateDialog] = useState(false);

  // Build filters object
  const filters: ContentIdeaFilters = useMemo(() => {
    const result: ContentIdeaFilters = {};
    if (searchQuery.trim()) result.search = searchQuery.trim();
    if (statusFilter && statusFilter !== 'all') result.status = statusFilter as any;
    if (contentTypeFilter && contentTypeFilter !== 'all') result.content_type = contentTypeFilter;
    return result;
  }, [searchQuery, statusFilter, contentTypeFilter]);

  // Data fetching
  const {
    data: ideasResponse,
    isLoading,
    error,
    refetch
  } = useContentIdeas(filters, { page, limit: 10, sortBy, sortOrder });

  const { data: contentTypeOptions = [] } = useContentTypeOptions();

  // Mutations
  const deleteIdeaMutation = useDeleteContentIdea({
    onSuccess: () => {
      setDeleteIdea(null);
      refetch();
    }
  });

  const createBriefMutation = useCreateBriefFromIdea('', {
    onSuccess: () => {
      toast.success('Brief created from idea!');
    }
  });

  // Auto-generate mutation
  const autoGenerateMutation = useAutoGenerateIdeas({
    onSuccess: () => {
      refetch(); // Refresh the ideas list
    }
  });

  // Event handlers
  const handleSort = (key: string) => {
    if (sortBy === key) {
      setSortOrder(sortOrder === 'asc' ? 'desc' : 'asc');
    } else {
      setSortBy(key);
      setSortOrder('asc');
    }
  };


  const handleDelete = useCallback((idea: ContentIdeaWithDetails) => {
    setDeleteIdea(idea);
  }, []);

  const confirmDelete = useCallback(() => {
    if (deleteIdea) {
      deleteIdeaMutation.mutate(deleteIdea.id);
    }
  }, [deleteIdea, deleteIdeaMutation]);

  const handleCreateBriefFromIdea = (idea: ContentIdeaWithDetails) => {
    onCreateBrief(idea);
  };

  const handleItemSelect = (itemId: string, selected: boolean) => {
    setSelectedItems(prev => 
      selected 
        ? [...prev, itemId]
        : prev.filter(id => id !== itemId)
    );
  };

  const handleSelectAll = (selected: boolean) => {
    setSelectedItems(selected ? (ideasResponse?.data.map(item => item.id) || []) : []);
  };


  const handleAutoGenerate = () => {
    setShowAutoGenerateDialog(true);
  };

  const handleAutoGenerateSubmit = async (data: AutoGenerateFormData) => {
    await autoGenerateMutation.mutateAsync({
      contentType: data.contentType,
      targetAudience: data.targetAudience
    });
  };

  const handleBulkExport = () => {
    if (selectedItems.length === 0) {
      toast.error('Please select ideas to export');
      return;
    }
    
    toast.info('Bulk export coming soon!', {
      description: `Export ${selectedItems.length} selected ideas to CSV/JSON.`
    });
  };

  const handleBulkDelete = () => {
    if (selectedItems.length === 0) {
      toast.error('Please select ideas to delete');
      return;
    }
    
    // For now, show a confirmation toast
    toast.info(`Delete ${selectedItems.length} selected ideas?`, {
      description: 'This will permanently delete the selected content ideas.',
      action: {
        label: 'Delete',
        onClick: () => {
          // TODO: Implement bulk delete mutation
          toast.success(`${selectedItems.length} ideas deleted successfully`);
          setSelectedItems([]);
        }
      }
    });
  };

  // Column configuration with memoization
  const columns = useMemo(() => getContentIdeaColumns({
    onEdit: onEditIdea,
    onDelete: handleDelete,
    onCreateBrief: handleCreateBriefFromIdea,
    onViewBrief
  }), [onEditIdea, handleDelete, handleCreateBriefFromIdea, onViewBrief]);

  // Loading state
  if (isLoading) {
    return (
      <div className={className}>
        <div className="space-y-6">
          {/* Header skeleton */}
          <div className="flex flex-col sm:flex-row gap-4">
            <Skeleton className="h-10 flex-1" />
            <Skeleton className="h-10 w-32" />
            <Skeleton className="h-10 w-40" />
          </div>
          
          {/* Action buttons skeleton */}
          <div className="flex flex-col sm:flex-row gap-4">
            <Skeleton className="h-10 flex-1" />
            <Skeleton className="h-10 w-32" />
            <Skeleton className="h-10 w-32" />
          </div>

          {/* Table skeleton */}
          <div className="space-y-3">
            {[...Array(5)].map((_, i) => (
              <Skeleton key={i} className="h-16 w-full" />
            ))}
          </div>
        </div>
      </div>
    );
  }

  // Error state
  if (error) {
    return (
      <div className={className}>
        <div className="text-center py-8">
          <div className="text-destructive mb-2">Error loading content ideas</div>
          <div className="text-sm text-muted-foreground mb-4">{error.message}</div>
          <Button onClick={() => refetch()} variant="outline">
            Try Again
          </Button>
        </div>
      </div>
    );
  }

  const ideas = ideasResponse?.data || [];
  const totalCount = ideasResponse?.pagination.total || 0;

  return (
    <div className={className}>
      {/* Header with title and description */}
      <div className="mb-6">
        <div className="flex items-center gap-3 mb-2">
          <div className="p-2 bg-yellow-100 dark:bg-yellow-900/20 rounded-lg">
            <Lightbulb className="h-5 w-5 text-yellow-600 dark:text-yellow-400" />
          </div>
          <div>
            <h2 className="text-xl font-semibold">Generate Ideas</h2>
            <p className="text-sm text-muted-foreground">
              Create and manage content ideas for your marketing campaigns
            </p>
          </div>
        </div>
        
        {totalCount > 0 && (
          <div className="flex items-center gap-2">
            <Badge variant="outline" className="text-sm">
              {totalCount} idea{totalCount === 1 ? '' : 's'}
            </Badge>
            {selectedItems.length > 0 && (
              <Badge variant="secondary" className="text-sm">
                {selectedItems.length} selected
              </Badge>
            )}
          </div>
        )}
      </div>

      {/* Action Buttons Row */}
      <div className="flex flex-col sm:flex-row gap-4 mb-6">
        <div className="flex gap-2">
          <Button onClick={handleAutoGenerate} className="flex items-center gap-2">
            <Bot className="h-4 w-4" />
            Auto Generate
          </Button>
        </div>
        
        <div className="flex gap-2 sm:ml-auto">
          {selectedItems.length > 0 && (
            <>
              <Button onClick={handleBulkDelete} variant="outline" size="sm" className="text-destructive hover:text-destructive">
                <Trash2 className="h-4 w-4 mr-2" />
                Delete ({selectedItems.length})
              </Button>
              <Button onClick={handleBulkExport} variant="outline" size="sm">
                <Download className="h-4 w-4 mr-2" />
                Export ({selectedItems.length})
              </Button>
            </>
          )}
          <Button onClick={onCreateIdea} variant="outline" className="flex items-center gap-2">
            <Plus className="h-4 w-4" />
            New Idea
          </Button>
        </div>
      </div>

      {/* Filters Row */}
      <div className="flex flex-col sm:flex-row gap-4 mb-6">
        <div className="relative flex-1">
          <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-muted-foreground" />
          <Input
            placeholder="Search ideas by title, description, or keywords..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="pl-10"
          />
        </div>
        
        <Select value={statusFilter} onValueChange={setStatusFilter}>
          <SelectTrigger className="w-32 mx-auto">
            <Filter className="h-4 w-4 mr-2" />
            <SelectValue placeholder="Status" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all">All Status</SelectItem>
            {CONTENT_STATUSES.IDEAS.map((status) => (
              <SelectItem key={status.value} value={status.value}>
                {status.label}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>

        <Select value={contentTypeFilter} onValueChange={setContentTypeFilter}>
          <SelectTrigger className="w-40 mx-auto">
            <SelectValue placeholder="Content Type" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all">All Types</SelectItem>
            {contentTypeOptions.map((option) => (
              <SelectItem key={option.value} value={option.value}>
                {option.label}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
      </div>

      {/* Data Table or Empty State */}
      {ideas.length === 0 ? (
        <EmptyState
          icon={Lightbulb}
          title={searchQuery || statusFilter !== 'all' || contentTypeFilter !== 'all' 
            ? "No ideas found" 
            : "No content ideas yet"
          }
          description={
            searchQuery || statusFilter !== 'all' || contentTypeFilter !== 'all'
              ? "Try adjusting your search filters"
              : "Create your first content idea to start brainstorming your next marketing campaign"
          }
          action={
            !searchQuery && statusFilter === 'all' && contentTypeFilter === 'all' ? (
              <div className="flex gap-2">
                <Button onClick={onCreateIdea} className="flex items-center gap-2">
                  <Plus className="h-4 w-4" />
                  Create First Idea
                </Button>
                <Button onClick={handleAutoGenerate} variant="outline">
                  <Bot className="h-4 w-4 mr-2" />
                  Auto Generate
                </Button>
              </div>
            ) : undefined
          }
        />
      ) : (
        <DataTable
          data={ideas}
          columns={columns}
          selectedItems={selectedItems}
          onItemSelect={handleItemSelect}
          onSelectAll={handleSelectAll}
          getItemId={(item) => item.id}
          sortBy={sortBy}
          sortOrder={sortOrder}
          onSort={handleSort}
          isLoading={isLoading}
          emptyMessage="No ideas match your criteria"
          className="rounded-lg border"
        />
      )}

      {/* Pagination */}
      {ideasResponse && ideasResponse.pagination.totalPages > 1 && (
        <div className="flex items-center justify-between mt-6">
          <div className="text-sm text-muted-foreground">
            Showing {(page - 1) * 10 + 1} to {Math.min(page * 10, totalCount)} of {totalCount} ideas
          </div>
          <div className="flex gap-2">
            <Button 
              variant="outline" 
              size="sm"
              onClick={() => setPage(p => Math.max(1, p - 1))}
              disabled={!ideasResponse.pagination.hasPreviousPage}
            >
              Previous
            </Button>
            <Button 
              variant="outline" 
              size="sm"
              onClick={() => setPage(p => p + 1)}
              disabled={!ideasResponse.pagination.hasNextPage}
            >
              Next
            </Button>
          </div>
        </div>
      )}

      {/* Delete Confirmation Dialog */}
      <AlertDialog open={!!deleteIdea} onOpenChange={() => setDeleteIdea(null)}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Delete Content Idea</AlertDialogTitle>
            <AlertDialogDescription>
              Are you sure you want to delete "{deleteIdea?.title}"? This action cannot be undone.
              {deleteIdea?.briefs_count && deleteIdea.briefs_count > 0 && (
                <div className="mt-2 text-sm font-medium text-amber-600">
                  Warning: This idea has {deleteIdea.briefs_count} associated brief{deleteIdea.briefs_count > 1 ? 's' : ''}. 
                  They will remain but will lose the connection to this idea.
                </div>
              )}
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancel</AlertDialogCancel>
            <AlertDialogAction 
              onClick={confirmDelete}
              disabled={deleteIdeaMutation.isPending}
              className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
            >
              {deleteIdeaMutation.isPending ? 'Deleting...' : 'Delete'}
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>

      {/* Auto Generate Dialog */}
      <AutoGenerateDialog
        isOpen={showAutoGenerateDialog}
        onClose={() => setShowAutoGenerateDialog(false)}
        onSubmit={handleAutoGenerateSubmit}
        isLoading={autoGenerateMutation.isPending}
      />
    </div>
  );
});

GenerateIdeasTab.displayName = 'GenerateIdeasTab';